//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnswerService.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnswerService.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer already accepted.
        /// </summary>
        public static string AnswerAlreadyAccepted {
            get {
                return ResourceManager.GetString("AnswerAlreadyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer already exists.
        /// </summary>
        public static string AnswerAlreadyExists {
            get {
                return ResourceManager.GetString("AnswerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer not accepted.
        /// </summary>
        public static string AnswerNotAccepted {
            get {
                return ResourceManager.GetString("AnswerNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer not found.
        /// </summary>
        public static string AnswerNotFound {
            get {
                return ResourceManager.GetString("AnswerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сan&apos;t vote for your own post.
        /// </summary>
        public static string CannotVoteForOwnPost {
            get {
                return ResourceManager.GetString("CannotVoteForOwnPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid answer body.
        /// </summary>
        public static string InvalidAnswerBody {
            get {
                return ResourceManager.GetString("InvalidAnswerBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation forbidden.
        /// </summary>
        public static string OperationForbidden {
            get {
                return ResourceManager.GetString("OperationForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This question already has accepted answer.
        /// </summary>
        public static string QuestionAlreadyHasAcceptedAnswer {
            get {
                return ResourceManager.GetString("QuestionAlreadyHasAcceptedAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not found.
        /// </summary>
        public static string QuestionNotFound {
            get {
                return ResourceManager.GetString("QuestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions not found.
        /// </summary>
        public static string QuestionsNotFound {
            get {
                return ResourceManager.GetString("QuestionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too low reputation.
        /// </summary>
        public static string TooLowReputation {
            get {
                return ResourceManager.GetString("TooLowReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users not found.
        /// </summary>
        public static string UsersNotFound {
            get {
                return ResourceManager.GetString("UsersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote already given.
        /// </summary>
        public static string VoteAlreadyGiven {
            get {
                return ResourceManager.GetString("VoteAlreadyGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote not found.
        /// </summary>
        public static string VoteNotFound {
            get {
                return ResourceManager.GetString("VoteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes not found.
        /// </summary>
        public static string VotesNotFound {
            get {
                return ResourceManager.GetString("VotesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote type not found.
        /// </summary>
        public static string VoteTypeNotFound {
            get {
                return ResourceManager.GetString("VoteTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote types not found.
        /// </summary>
        public static string VoteTypesNotFound {
            get {
                return ResourceManager.GetString("VoteTypesNotFound", resourceCulture);
            }
        }
    }
}
